# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'rest-client'
require 'json'

Plant.destroy_all
User.destroy_all

# tree_data = RestClient.get('https://trefle.io/api/plants?token=dzhxS1ZtNnQyT1NnMDRxZEd3a2llZz09&page_size=50&complete_data&q=tree')
# parsed_data = JSON.parse(tree_data)
#
# parsed_data.each do |plant|
#   raw_data2 = RestClient.get("http://trefle.io/api/plants/#{plant['id']}?token=dzhxS1ZtNnQyT1NnMDRxZEd3a2llZz09")
#   parsed_data2 = JSON.parse(raw_data2)
#
#   if (parsed_data2["complete_data"] == true)
#     Plant.create({
#         name: parsed_data2["main_species"]["common_name"],
#         scientific_name: parsed_data2["scientific_name"],
#         family_name: parsed_data2["varieties"][0]["family_common_name"]
#         # img: parsed_data2["main_species"]["images"][0]["url"],
#         # flower_color: parsed_data2["main_species"]["flower"]["color"],
#         # foliage_texture: "",
#         # foliage_color: "",
#         # growth_period: "",
#         # bloom_period: "",
#         # shade_tolerance: "",
#         # temperature_mininum: "",
#         # ph_minimum: "",
#         # ph_maximum: "",
#         # drought_tolerance: "",
#         # duration: "",
#         # mature_height: ""
#     })
#   end
# end

plants = [
    {
      "name" => "Slender Pride of Rochester",
      "scientific_name" => "Deutzia Gracilis",
      "family_name" => "Hydrangea",
      "img" => "https://upload.wikimedia.org/wikipedia/commons/7/7e/Deutzia_gracilis_A.jpg",
      "flower_color" => "White",
      "foliage_texture" => "Medium",
      "foliage_color" => "Green",
      "growth_period" => "Spring and Summer",
      "bloom_period" => "Mid Spring",
      "shade_tolerance" => "Intermediate",
      "temperature_minimum" => "-23 Fahr",
      "ph_minimum" => "5",
      "ph_maximum" => "7",
      "drought_tolerance" => "Low",
      "duration" => "Perennial",
      "mature_height" => "3 ft",
      "growability" => 5,
      "plant_type" => "Flower"
    },
    {
      "name" => "Rayless Arnica",
      "scientific_name" => "Arnica Diversifolia",
      "family_name" => "Aster",
      "img" => "https://static.inaturalist.org/photos/3814754/original.jpg?1464203805",
      "flower_color" => "Yellow",
      "foliage_texture" => "Coarse",
      "foliage_color" => "Green",
      "growth_period" => "Summer",
      "bloom_period" => "Summer",
      "shade_tolerance" => "Intermediate",
      "temperature_minimum" => "-23 Fahr",
      "ph_minimum" => "6.3",
      "ph_maximum" => "7.8",
      "drought_tolerance" => "None",
      "duration" => "Perennial",
      "mature_height" => "1.3 ft",
      "growability" => 6,
      "plant_type" => "Flower"
    },
    {
      "name" => "Virginica Iris",
      "scientific_name" => "Iris Virginica var. Virginica",
      "family_name" => "Iris",
      "img" => "https://nature.mdc.mo.gov/sites/default/files/styles/centered_full/public/media/field-guide/southern%20blue%20flag.jpg?itok=BVQzu0MD",
      "flower_color" => "Blue",
      "foliage_texture" => "Coarse",
      "foliage_color" => "Green",
      "growth_period" => "Spring",
      "bloom_period" => "Spring",
      "shade_tolerance" => "Tolerant",
      "temperature_minimum" => "12 Fahr",
      "ph_minimum" => "4.8",
      "ph_maximum" => "7.3",
      "drought_tolerance" => "None",
      "duration" => "Perennial",
      "mature_height" => "3.3 ft",
      "growability" => 4,
      "plant_type" => "Flower"
    },
    {
      "name" => "Utah Juniper",
      "scientific_name" => "Juniperus Osteosperma",
      "family_name" => "Cypress",
      "img" => "https://imgc.allpostersimages.com/img/print/u-g-Q10EAYC0.jpg?w=550&h=550&p=0",
      "flower_color" => "Yellow",
      "foliage_texture" => "Medium",
      "foliage_color" => "Green",
      "growth_period" => "Spring and Summer",
      "bloom_period" => "Early Spring",
      "shade_tolerance" => "Intolerant",
      "temperature_minimum" => "-28 Fahr",
      "ph_minimum" => "6.5",
      "ph_maximum" => "8.2",
      "drought_tolerance" => "High",
      "duration" => "Perennial",
      "mature_height" => "26 ft",
      "growability" => 2,
      "plant_type" => "Tree"
    },
    {
      "name" => "Low Pussytoes",
      "scientific_name" => "Antennaria Dimorpha var. Integra",
      "family_name" => "Aster",
      "img" => "https://upload.wikimedia.org/wikipedia/commons/9/9d/Antennaria_dimorpha_1.jpg",
      "flower_color" => "Purple",
      "foliage_texture" => "Fine",
      "foliage_color" => "Color",
      "growth_period" => "Spring and Summer",
      "bloom_period" => "Late Spring",
      "shade_tolerance" => "Intermediate",
      "temperature_minimum" => "-38 Fahr",
      "ph_minimum" => "5.8",
      "ph_maximum" => "7.8",
      "drought_tolerance" => "High",
      "duration" => "Perennial",
      "mature_height" => "0.3 ft",
      "growability" => 5,
      "plant_type" => "Flower"
    },
    {
      "name" => "Golden Bamboo",
      "scientific_name" => "Phyllostachys Aurea",
      "family_name" => "Grass",
      "img" => "https://upload.wikimedia.org/wikipedia/commons/3/3b/Phyllostachys_aurea0.jpg",
      "flower_color" => "n/a",
      "foliage_texture" => "Coarse",
      "foliage_color" => "Green",
      "growth_period" => "Spring, Summer, Fall",
      "bloom_period" => "n/a",
      "shade_tolerance" => "Intolerant",
      "temperature_minimum" => "-3 Fahr",
      "ph_minimum" => "5",
      "ph_maximum" => "7.5",
      "drought_tolerance" => "Low",
      "duration" => "Perennial",
      "mature_height" => "15 ft",
      "growability" => 4,
      "plant_type" => "Grass"
    },
    {
      "name" => "Greenwhite Sedge",
      "scientific_name" => "Carex Albolutescens",
      "family_name" => "Sedge",
      "img" => "https://lh5.googleusercontent.com/-TP01LoW2iN4/U87zzmdwr8I/AAAAAAAASUc/S2JWL92psK4/s512/Carex%2520albolutescens.ElkNeckSFShootingRange.062314_l.jpg",
      "flower_color" => "Green",
      "foliage_texture" => "Fine",
      "foliage_color" => "Green",
      "growth_period" => "Moderate",
      "bloom_period" => "Spring",
      "shade_tolerance" => "Intermediate",
      "temperature_minimum" => "-38 Fahr",
      "ph_minimum" => "4.3",
      "ph_maximum" => "7.8",
      "drought_tolerance" => "Low",
      "duration" => "Perennial",
      "mature_height" => "3.9 ft",
      "growability" => 6,
      "plant_type" => "Other"
    },
    {
      "name" => "Blackbrush",
      "scientific_name" => "Coleogyne Ramosissima",
      "family_name" => "Rose",
      "img" => "https://www.swcoloradowildflowers.com/Yellow%20Enlarged%20Photos/4cora.jpg",
      "flower_color" => "Yellow",
      "foliage_texture" => "Coarse",
      "foliage_color" => "White-Gray",
      "growth_period" => "Summer",
      "bloom_period" => "Mid Spring",
      "shade_tolerance" => "Intolerant",
      "temperature_minimum" => "-18 Fahr",
      "ph_minimum" => "5.9",
      "ph_maximum" => "8",
      "drought_tolerance" => "High",
      "duration" => "Perennial",
      "mature_height" => "6 ft",
      "growability" => 7,
      "plant_type" => "Flower"
    },
    {
      "name" => "European Lily of the Valley",
      "scientific_name" => "Convallaria Majalis var. Montana",
      "family_name" => "Lily",
      "img" => "https://www.whiteflowerfarm.com/mas_assets/cache/image/2/7/3/6/10038.Jpg",
      "flower_color" => "White",
      "foliage_texture" => "Medium",
      "foliage_color" => "Green",
      "growth_period" => "Summer",
      "bloom_period" => "Summer",
      "shade_tolerance" => "Tolerant",
      "temperature_minimum" => "-33 Fahr",
      "ph_minimum" => "5.5",
      "ph_maximum" => "7.5",
      "drought_tolerance" => "Low",
      "duration" => "Perennial",
      "mature_height" => "0.8 ft",
      "growability" => 5,
      "plant_type" => "Flower"
    },
    {
      "name" => "Lanceleaf Grapefern",
      "scientific_name" => "Botrychium Lanceolatum Ssp. Angustisegmentum",
      "family_name" => "Adder's-tongue",
      "img" => "https://newfs.s3.amazonaws.com/taxon-images-1000s1000/Ophioglossaceae/botrychium-angustisegmentum-le-dcameron.jpg",
      "flower_color" => "n/a",
      "foliage_texture" => "Fine",
      "foliage_color" => "Green",
      "growth_period" => "Spring",
      "bloom_period" => "Summer",
      "shade_tolerance" => "Tolerant",
      "temperature_minimum" => "-33 Fahr",
      "ph_minimum" => "4.4",
      "ph_maximum" => "6",
      "drought_tolerance" => "None",
      "duration" => "Perennial",
      "mature_height" => "0.9 ft",
      "growability" => 8,
      "plant_type" => "Other"
    },
    {
      "name" => "Husk Tomato",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://i.pinimg.com/originals/76/14/34/761434572a0ded6cb8df3054d74d0e29.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 8,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Currant Tomato",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://www.tomatogrowers.com/images/5362.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 7,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Yellow Monster Pepper",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.rareseeds.com/assets/1/14/DimRegular/pepper-yellow-monster.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 9,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Cosmic Purple Carrot",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://images-na.ssl-images-amazon.com/images/I/51i4cK4bZlL._SX425_.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 7,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Vidi Red Bell Pepper",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.grow-it-organically.com/images/pepper-f-lipstick-hand1-l.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 9,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Yellow (of Parma) Onion",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://www.southernexposure.com/images/large/onions-yellow-of-parma_LRG.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 10,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Russet Potato",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://bloximages.chicago2.vip.townnews.com/idahostatejournal.com/content/tncms/assets/v3/editorial/a/52/a52a0a0a-48ac-5552-8a12-e357fe0e5fc2/5aa1b572d8a08.image.jpg?resize=400%2C232",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 7,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Yellow Carnation",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://phototrap.files.wordpress.com/2014/05/carnationflowers14.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 5,
      "plant_type" => "Flower"
    },
    {
      "name" => "Scallion",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://harvesttotable.com/wp-content/uploads/2011/05/Onion-Row1.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 10,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Yolo Wonder Bell Pepper",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://www.wildroseheritageseed.com/uploads/4/2/2/4/42241473/s145558776392258095_p41_i33_w640.jpeg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 8,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Garlic",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://hgtvhome.sndimg.com/content/dam/images/hgtv/stock/2018/3/22/01/shutterstock_gunsan-gimbanjang_647022712_garlic.jpg.rend.hgtvcom.616.411.suffix/1521751497410.jpeg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 9,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Purple Japanese Sweet Potato",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://www.specialtyproduce.com/sppics/9713.png",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 7,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Foxgloves",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://media.mnn.com/assets/images/2016/02/foxglove.jpg.638x0_q80_crop-smart.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 6,
      "plant_type" => "Flower"
    },
    {
      "name" => "Aloe Vera",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://imgix.bustle.com/uploads/image/2017/8/25/c9612a69-f227-411b-9c15-5ccecb0452f4-aloe-vera-2623317_1920.jpg?w=960&h=540&fit=crop&crop=faces&auto=format&q=70",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 10,
      "plant_type" => "Succulent"
    },
    {
      "name" => "Fiddle Leaf Fig",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/fiddle-leaf-fig-care-1527631142.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 9,
      "plant_type" => "Tree"
    },
    {
      "name" => "Black Calla Lily",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.brecks.com/images/500/39617.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 3,
      "plant_type" => "Flower"
    },
    {
      "name" => "Basil",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://cdn1.medicalnewstoday.com/content/images/articles/266/266425/basil-with-wet-leaves.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 10,
      "plant_type" => "Herb"
    },
    {
      "name" => "Thyme",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://www.herbco.com/images/Category/large/c-166-thyme.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 10,
      "plant_type" => "Herb"
    },
    {
      "name" => "Lambert Cherry",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.piskinfidancilik.com.tr/en/images/450x280/kiraz/LAMBERT_18.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 4,
      "plant_type" => "Fruit"
    },
    {
      "name" => "Fuji Apple",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://www.erinnudi.com/wp-content/uploads/2014/09/apples-1947711_1920.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 5,
      "plant_type" => "Fruit"
    },
    {
      "name" => "Tobacco",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.lovethegarden.com/sites/default/files/IMG_0364_young_plants2.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 3,
      "plant_type" => "Other"
    },
    {
      "name" => "Blueberry",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://cdn.shopify.com/s/files/1/0089/1562/products/blueberry.png?v=1516598393",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 6,
      "plant_type" => "Fruit"
    },
    {
      "name" => "Sunflower (common)",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://tenrandomfacts.com/wp-content/uploads/2016/08/Common-Sunflower.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 8,
      "plant_type" => "Flower"
    },
    {
      "name" => "Carrot (common)",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://secure.i.telegraph.co.uk/multimedia/archive/01518/carrots-lifted_1518277c.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 8,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Mint",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://migardener.com/wp-content/uploads/2018/04/mint.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 7,
      "plant_type" => "Herb"
    },
    {
      "name" => "Rose (common)",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://dxewmvd5ovjsu.cloudfront.net/media/ROSES/loving-memory-rose.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 7,
      "plant_type" => "Flower"
    },
    {
      "name" => "Weeping Willow",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://cdn11.bigcommerce.com/s-vze7h4ezaf/images/stencil/800x800/products/366/1432/shutterstock_628403774__51361.1509235302__46291.1515818943.jpg?c=2",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 4,
      "plant_type" => "Flower"
    },
    {
      "name" => "Orange",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://lemoncitrustree.com/store/media/catalog/product/cache/1/image/1200x1200/9df78eab33525d08d6e5fb8d27136e95/c/a/calamondin-orange_4.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 2,
      "plant_type" => "Fruit"
    },
    {
      "name" => "Morning Glory",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.planetnatural.com/wp-content/uploads/2012/12/morning-glory-flower.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 9,
      "plant_type" => "Flower"
    },
    {
      "name" => "Corn",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2014/08/26/101947571-180198107.530x298.jpg?v=1409060170",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 4,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Cucumber",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://images-na.ssl-images-amazon.com/images/I/81Lgy6gyD5L._SL1500_.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 5,
      "plant_type" => "Vegetable"
    },
    {
      "name" => "Birds of Paradise",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.ftd.com/blog/content/uploads/2016/08/hero-birdofparadise-720x480.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 4,
      "plant_type" => "Flower"
    },
    {
      "name" => "Peyote",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://drugfree.org/wp-content/uploads/2017/02/peyote.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 2,
      "plant_type" => "Succulent"
    },
    {
      "name" => "Hedgehog Cacti",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://upload.wikimedia.org/wikipedia/en/6/61/Strawberry_Hedgehog.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 1,
      "plant_type" => "Succulent"
    },
    {
      "name" => "Japanese Maple",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.gardendesign.com/pictures/images/900x705Max/site_3/japanese-maple-tree-acer-palmatum-dreamstime_12239.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 3,
      "plant_type" => "Tree"
    },
    {
      "name" => "Southern Magnolia",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://cdn11.bigcommerce.com/s-f74ff/images/stencil/800x800/products/10430/26894/screen-shot-2017-10-10-at-6-39-07-pm__39437.1538956570.png?c=2",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 7,
      "plant_type" => "tree"
    },
    {
      "name" => "Witch Hazel",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "https://www.gardendesign.com/pictures/images/675x529Max/site_3/yellow-witch-hazel-hamamelis-primavers-garden-design_11671.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 6,
      "plant_type" => "tree"
    },
    {
      "name" => "Devil's Ivy",
      "scientific_name" => "",
      "family_name" => "",
      "img" => "http://www.baag.com.au/wp-content/uploads/epipremnum_aureum.jpg",
      "flower_color" => "",
      "foliage_texture" => "",
      "foliage_color" => "",
      "growth_period" => "",
      "bloom_period" => "",
      "shade_tolerance" => "",
      "temperature_minimum" => "",
      "ph_minimum" => "",
      "ph_maximum" => "",
      "drought_tolerance" => "",
      "duration" => "",
      "mature_height" => "",
      "growability" => 8,
      "plant_type" => "other"
    }
]

plants.each do |plantObj|
  hash = {}

  plantObj.each do |k,v|
    hash[k] = v
  end

  Plant.create(hash)
end


User.create(
  username: "johnny845",
  name: "Jonathan Choi",
  city: "Boston"
)

User.create(
  username: "martymar90",
  name: "Marty Mar",
  city: "Detroit"
)
User.create(
  username: "GeorgeLikesHisChickenSpicy",
  name: "George Costanza",
  city: "New York"
)
